package cn.iocoder.yudao.module.system.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum PlatformCodeEnum {

    OK("OK", "成功"),
    API_IP_BLOCKED("API_IP_BLOCKED", "IP禁止访问"),
    DOWN_STREAM_ERROR("DOWN_STREAM_ERROR", "下发异常"),
    INVALID_BALANCE("INVALID_BALANCE", "金额错误"),
    UNKNOWN_ERROR("UNKNOWN_ERROR", "未知错误"),
    INVALID_REQUEST("INVALID_REQUEST", "请求参数错误或缺失"),
    AUTHENTICATION_FAILED("AUTHENTICATION_FAILED", "认证失败"),
    INVALID_SIGNATURE("INVALID_SIGNATURE", "签名验证失败"),
    INVALID_TOKEN("INVALID_TOKEN", "Token 无效"),
    INVALID_GAME("INVALID_GAME", "游戏无效"),

    DUPLICATE_REQUEST("DUPLICATE_REQUEST", "重复请求"),
    CURRENCY_NOT_SUPPORTED("CURRENCY_NOT_SUPPORTED", "不支持该货币"),
    WRONG_CURRENCY("WRONG_CURRENCY", "钱包货币不匹配"),
    INSUFFICIENT_FUNDS("INSUFFICIENT_FUNDS", "余额不足"),

    USER_NOT_EXISTS("USER_NOT_EXISTS", "用户不存在"),
    USER_DISABLED("USER_DISABLED", "用户被禁用"),

    TRANSACTION_DUPLICATED("TRANSACTION_DUPLICATED", "交易重复"),
    TRANSACTION_NOT_EXISTS("TRANSACTION_NOT_EXISTS", "交易不存在"),

    VENDOR_ERROR("VENDOR_ERROR", "供应商错误"),
    TENANT_ERROR("VENDOR_ERROR", "账号错误"),
    UNDER_MAINTENANCE("UNDER_MAINTENANCE", "维护中"),

    MISMATCHED_DATA_TYPE("MISMATCHED_DATA_TYPE", "数据类型错误"),
    INVALID_RESPONSE("INVALID_RESPONSE", "无效响应"),

    INVALID_VENDOR("INVALID_VENDOR", "供应商无效"),
    INVALID_LANGUAGE("INVALID_LANGUAGE", "语言不支持"),

    GAME_DISABLED("GAME_DISABLED", "游戏已禁用"),
    INVALID_PLATFORM("INVALID_PLATFORM", "平台无效"),

    GAME_LANGUAGE_NOT_SUPPORTED("GAME_LANGUAGE_NOT_SUPPORTED", "游戏语言不支持"),
    GAME_PLATFORM_NOT_SUPPORTED("GAME_PLATFORM_NOT_SUPPORTED", "游戏平台不支持"),
    GAME_CURRENCY_NOT_SUPPORTED("GAME_CURRENCY_NOT_SUPPORTED", "游戏货币不支持"),

    VENDOR_LINE_DISABLED("VENDOR_LINE_DISABLED", "供应商线路禁用"),
    VENDOR_CURRENCY_NOT_SUPPORTED("VENDOR_CURRENCY_NOT_SUPPORTED", "供应商货币不支持"),
    VENDOR_LANGUAGE_NOT_SUPPORTED("VENDOR_LANGUAGE_NOT_SUPPORTED", "供应商语言不支持"),
    VENDOR_PLATFORM_NOT_SUPPORTED("VENDOR_PLATFORM_NOT_SUPPORTED", "供应商平台不支持"),

    TRANSACTION_STILL_PROCESSING("TRANSACTION_STILL_PROCESSING", "交易处理中"),
    EXCEEDED_NUMBER_OF_RETRIES("EXCEEDED_NUMBER_OF_RETRIES", "超出重试次数"),
    OPERATOR_TIMEOUT("OPERATOR_TIMEOUT", "运营商超时"),

    INVALID_FROM_TIME("INVALID_FROM_TIME", "仅支持最近60天数据"),
    INVALID_DATE_RANGE("INVALID_DATE_RANGE", "日期范围必须一天内"),

    REFERENCE_ID_DUPLICATED("REFERENCE_ID_DUPLICATED", "参考ID重复"),
    TRANSACTION_DOES_NOT_EXIST("TRANSACTION_DOES_NOT_EXIST", "参考ID不存在"),

    INTERNAL_ERROR("INTERNAL_ERROR", "内部错误"),
    WALLET_NOT_SUPPORTED("WALLET_NOT_SUPPORTED", "钱包类型不支持"),
    TIMEOUT_ERROR("TIMEOUT_ERROR", "请求超时");

    private final String code;
    private final String message;


}